### ISSUE TITLE
Looks Good

### ISSUE THREAD

**Issue by dtderosa** [alphawolf918/PyNet#1]
This is very similar to the script I use.
A few differences from what I do on mine are:
-You use get_closest_server() and I am using get_best_server() - don't know what the difference or best practice is. I just basically followed and tweaked an example I found that used get_best_server()
-Try-Catch: I have a try-catch surrounding the attempt to insert data to DB to ensure connection closure in case something fails. I imagine not a big deal since the script just stops and dies after execution and probably doesn't leave a hanging connection anyway
-Logging of data Timestamp. This one I would think you could benefit from implementing. When was the data captured? You can 'import time' and then generate a variable containing the timestamp of the data run to log to the DB using something like 'timestamp = time.strftime('%Y-%m-%d %H:%M"%S
)' and throw that into a new datetime column in your table for reference later.

Good Job, BTW

**Comment by alphawolf918** [comment]
Thanks for the input! I'm logging the time as a CURRENT_TIMESTAMP on SQL
Server itself and it's formatted into a view so I can expand on it later.
:) I'll definitely add a try catch thing to it. From what I understand, the
get closest server just grabs the ones closest to your geographical
location, and I wanted to be as accurate as possible. Not sure if it makes
a big difference or not though. And I use get best server too, it actually
will throw an exception if you omit that as I found out. Thank you for the
feedback and if there's anything else you'd like to suggest I'd be happy to
hear it.

**Comment by dtderosa** [comment]
Ok, I was wondering why you didn't have a timestamp logging. So, you're doing it on the DB side? How is that implemented? Does the table have a trigger or something or a default value for the field that just defaults to the current time?

The try-catch and the best_server vs closest_server are just little differences I noticed from the script I have running. Like you said though - it may well not make a difference at all which one you use for the server and the try-catch was just mostly habit and could well not be necessary, especially if you aren't logging a failure in the DB in the catch block.... could just let it ride and die without bothering with adding the try-catch...

Good job. Now for a front-end to showcase your results :)

**Comment by alphawolf918** [comment]
Working on the front end in C# now, should be uploaded to my GitHub in a couple hours, maybe less. :) Yeah the SQL Server logged_on field is a Datetime with CURRENT_TIMESTAMP as a default.

**Comment by alphawolf918** [comment]
https://github.com/alphawolf918/PyNetManager

C# front-end. I got a screenshot on my phone to show ya tomorrow.
